### PR TITLE
feat: move over initial helper functions

### PR DESCRIPTION
**Pull request by mhdawson**
Move over two functions from npm-start packge which are already in their own files and have their own tests

## Summary

Refs: https://github.com/paketo-buildpacks/rfcs/blob/main/text/nodejs/0016-reduce-duplication-allow-sharing.md

## Use Cases

Copies over existing project_path_parser and package_json_parser from [npm-start](https://github.com/paketo-buildpacks/npm-start) package so that they can be re-used. Code files and test files were copied over unchanged except for changing package definition.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Comment by ryanmoran** [comment]
@mhdawson I would like to take this chance to refine the API for these helpers a bit. Now that they will live in a library that will need to be versioned and maintained with an eye towards backwards-compatibility, there are some bits of this specific code that could be better. Should I leave a detailed review of what I'd like to see, or just go ahead and make those changes myself?

**Comment by mhdawson** [comment]
@ryanmoran I'm happy if you want to push your changes.

**Comment by mhdawson** [comment]
@ryanmoran and really either way  up to you.

**Comment by ryanmoran** [comment]
I've made some changes to hopefully remove a bit of cruft. Let me know what y'all think, @mhdawson, @thitch97 @TisVictress

**Comment by mhdawson** [comment]
@ryanmoran looks good to me.

**Review by ryanmoran — APPROVED** [review]

**Pull request merged**
